### ISSUE TITLE
No content-type with multerS3.AUTO_CONTENT_TYPE and SVG

### ISSUE THREAD

**Issue by JustDoItSascha** [anacronw/multer-s3#126]
Hey!

I got an error that was hard to debug, but I think I found the issue:

In your multerS3.AUTO_CONTENT_TYPE function, you do

```
file.stream.once('data' ...)
```

On production servers the stream is not completed when the `once('data')` is firing. Later on you put the firstChunk in the function isSvg(). But this function needs to have the whole content, because it's checking whether the SVG is properly closed. Since you give it just a part of the SVG, the check always fails and SVG images get the wrong content-type when uploading to S3.

Should I open a pull request for this?

**Comment by lehni** [comment]
I am seeing this problem too. The issue is that whenever `firstChunk` isn't actually the full SVG, `is-svg` returns false, since it's using an XML parser to look at the file.

**Comment by lehni** [comment]
I ended up using a slightly different strategy than in https://github.com/JustDoItSascha/multer-s3/commit/9e4673bec97df0f37792a269adf76fcba1fa6cf7

I trust `file.mimetype` if provided, and fall back on trying to read the type from the first chunk. Only if that fails, the code keeps collecting chunks unitl the end and then runs the detection on the full data. 

```js
const contentType = (req, file, cb) => {
  const { mimetype, stream } = file
  if (mimetype) {
    cb(null, mimetype)
  } else {
    const chunks = []

    const done = type => {
      const outStream = new stream.PassThrough()
      for (const chunk of chunks) {
        outStream.write(chunk)
      }
      stream.pipe(outStream)
      cb(null, type, outStream)
    }

    const onData = chunk => {
      chunks.push(chunk)
      if (chunks.length === 1) {
        const type = FileType.fromBuffer(chunk)?.mime
        if (type) {
          stream.off('data', onData)
          done(type)
        } else {
          stream.once('end', () => {
            const data = Buffer.concat(chunks)
            const type = FileType.fromBuffer(data)?.mime || isSvg(data)
              ? 'image/svg+xml'
              : 'application/octet-stream'
            done(type)
          })
        }
      }
    }

    stream.on('data', onData)
  }
}
```

**Comment by danny-does-stuff** [comment]
Fix is in this PR https://github.com/anacronw/multer-s3/pull/103
