### ISSUE TITLE
Limit size 

### ISSUE THREAD

**Issue by Droppix** [anacronw/multer-s3#57]
Hi,

It's possible to fix limit size to upload?

Thkx

**Comment by LinusU** [comment]
Should be possible directly in multer

**Comment by josebrwn** [comment]
Setting limits { filesize : 1 } doesn't seem to work in multer-s3.

**Comment by nbeydoon** [comment]
Same here any update?

**Comment by nbeydoon** [comment]
Work for me

**Comment by arcalinea** [comment]
Also cannot set limits in multer-s3, and I don't see it specified anywhere in the code

**Comment by vijayant123** [comment]
I am also facing this issue. Following is my setup. Value of fileSize in limits is not checked by multer-s3 as per my tests. My current hack is to enclose the "multer()" upload middleware inside an empty middleware which first tests the content-length header in request before passing the request to multer. @LinusU, @badunk Please verify this at your end and tag this as a bug if fileSize does not work for you too.

var multerStorage = multerS3({
  s3: s3,
  bucket: process.env.AWS_S3_BUCKET,
  key: function (req, file, cb) {
    // key generation happens here
  }
});

// and use it as:
multer({
  storage: multerStorage,
  limits: {  
    fileSize: 209715200,
    files: 1000  
  },
  fileFilter: function (req, file, cb) {
    // file extension filtering happens here
  }
});

**Comment by LinusU** [comment]
If Multer doesn't respect the limits, please open an issue on Multer. Thanks!
