### ISSUE TITLE
 uploaded file 

### ISSUE THREAD

**Issue by kashikhan1** [anacronw/multer-s3#61]
why file is not opening in browers its only download from amazon

**Comment by LinusU** [comment]
This is probably due to headers/settings set on the uploaded file. Could you provide some more information?

**Comment by Kosai106** [comment]
I'm not sure why this issue hasn't been closed already. Anyway, I just had a similar question and it turns out that you'll need to set the content-type for the upload as such: `contentType: multerS3.AUTO_CONTENT_TYPE` then it should work just fine.
