### ISSUE TITLE
Minimum policy for uploading files to S3?

### ISSUE THREAD

**Issue by slavafomin** [anacronw/multer-s3#73]
Hello!

Thank you for this great module!

However, what would be the minimal possible AWS-policy needed for file upload using this module?

Thanks!

**Comment by LinusU** [comment]
I think that the only required action is `s3:PutObject`

**Comment by slavafomin** [comment]
@LinusU Sadly, it's not. That's the reason I've started this issue.

**Comment by LinusU** [comment]
Aha, what error do you get?

**Comment by slavafomin** [comment]
@LinusU it was a permission-related error, and as far as I remember, there were no specifics at what permissions were actually missing. Can't say for sure now, because I've switched to using `aws-sdk` module directly.

**Comment by pbojinov** [comment]
@slavafomin it looks like this project is using [s3fs](https://github.com/RiptideElements/s3fs) which requires the following IAM Policy:

```
{
  "Statement": [
    {
      "Action": [
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::your-bucket"
      ]
    },
    {
      "Action": [
        "s3:AbortMultipartUpload",
        "s3:CreateBucket",
        "s3:DeleteBucket",
        "s3:DeleteBucketPolicy",
        "s3:DeleteObject",
        "s3:GetBucketPolicy",
        "s3:GetLifecycleConfiguration",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:ListMultipartUploadParts",
        "s3:PutBucketPolicy",
        "s3:PutLifecycleConfiguration",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::your-bucket/*"
      ]
    }
  ]
}
```

**Comment by erulabs** [comment]
You'll need `s3:DeleteObject` to update files in place (which makes sense) and `s3:PutObjectAcl` to have multer set ACLs for you. My list looks like this:

```
              "s3:PutObject",
              "s3:GetObject",
              "s3:DeleteObject",
              "s3:GetObjectAcl",
              "s3:PutObjectAcl",
              "s3:UploadPart",
              "s3:UploadPartCopy"
```

**Comment by wedneyyuri** [comment]
> @slavafomin this is minimum AWS policy I am using my IAM user.
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "s3:PutObject"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::my_bucket_name/*"
>             ]
>         }
>     ]
> }
> ```

`s3:PutObjectAcl` is required to create public objects in S3.

**Comment by Warkanlock** [comment]
Amazon deprecated UploadPart action so is this the correct policy to upload, list, get and delete files using Multer on a bucket that's public:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:GetObjectAcl",
                "s3:PutObjectAcl",
            ],
            "Resource": [
                "arn:aws:s3:::my_bucket_name/*"
            ]
        }
    ]
}
```
