### ISSUE TITLE
No SSL Verification or HTTP

### ISSUE THREAD

**Issue by abonillabeeche** [anacronw/multer-s3#89]
Is there a way to avoid SSL verification ? I'm not using a public S3 endpoint - it is indeed listening on 80 and 443 - appending :80 won't make it use HTTP - Any hints are appreciated.

{ fieldname: 'upload',
  originalname: 'getHimOut.jpg',
  encoding: '7bit',
  mimetype: 'image/jpeg' }
{ Error: self signed certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
  message: 'self signed certificate',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: '...',
  retryable: true,
  time: 2017-12-14T17:04:07.771Z,
  storageErrors: [] }

**Comment by abonillasuse** [comment]
I've added
const ssl = new aws.S3({sslEnabled: '0'})

but don't know the expected option in the multerS3 side...

**Comment by LinusU** [comment]
You can pass in your own `S3` instance using the `s3` option
